CLOSED = 'closed'
CANCELLED = 'cancelled'
OPEN = 'open'
ANY = None

status_choices = (
    (ANY, 'Any'***REMOVED***,
    (OPEN, 'Open'***REMOVED***,
    (CLOSED, 'Closed'***REMOVED***,
    (CANCELLED, 'Cancelled'***REMOVED***,
***REMOVED***

#TODO: Add the rest
department_choices = (
    ('AEPS', 'AEPS-Ag and Environmental Plant Sci'***REMOVED***,
    ('AERO','AERO-Aerospace Engineering'***REMOVED***,
    ('AGB','AGB-Agribusiness'***REMOVED***,
    ('AG','AG-Agriculture'***REMOVED***,
    ('AGC','AGC-Agricultural Communication'***REMOVED***,
    ('AGED','AGED-Agricultural Education'***REMOVED***,
    ('ANT','ANT-Anthropology'***REMOVED***,
    ('ARCE','ARCE-Architectural Engineering'***REMOVED***,
    ('ARCH','ARCH-Architecture'***REMOVED***,
    ('ART','ART-Art'***REMOVED***,
    ('ASCI','ASCI-Animal Science'***REMOVED***,
    ('ASTR','ASTR-Astronomy'***REMOVED***,
    ('BIO','BIO-Biology'***REMOVED***,
    ('BMED','BMED-Biomedical Engineering'***REMOVED***,
    ('BOT','BOT-Botany'***REMOVED***,
    ('BRAE','BRAE-BioResource & Agricultural Eng'***REMOVED***,
    ('BUS','BUS-Business'***REMOVED***,
    ('CD','CD-Child Development'***REMOVED***,
    ('CE','CE-Civil Engineering'***REMOVED***,
    ('CHEM','CHEM-Chemistry'***REMOVED***,
    ('CHIN','CHIN-Chinese'***REMOVED***,
    ('CM','CM-Construction Management'***REMOVED***,
    ('COMS','COMS-Communication Studies'***REMOVED***,
    ('CPE','CPE-Computer Engineering'***REMOVED***,
    ('CRP','CRP-City and Regional Planning'***REMOVED***,
    ('CSC','CSC-Computer Science'***REMOVED***,
    ('DANC', 'DANC-Dance'***REMOVED***,
    ('DATA','DATA-Data Science'***REMOVED***,
    ('DSCI','DSCI-Dairy Science'***REMOVED***,
    ('ECON','ECON-Economics'***REMOVED***,
    ('EDES','EDES-Environmental Design'***REMOVED***,
    ('EDUC','EDUC-Education'***REMOVED***,
    ('EE','EE-Electrical Engineering'***REMOVED***,
    ('ENGL','ENGL-English'***REMOVED***,
    ('ENGR','ENGR-Engineering'***REMOVED***,
    ('ENVE', 'ENVE-Environmental Engineering'***REMOVED***,
    ('ERSC', 'ERSC-Earth Science'***REMOVED***,
    ('ES','ES-Ethnic Studies'***REMOVED***,
    ('FR', 'FR-French'***REMOVED***,
    ('ESE','ESE-Early Start English'***REMOVED***,
    ('ESM','ESM-Early Start Math'***REMOVED***,
    ('FSN','FSN-Food Science and Nutrition'***REMOVED***,
    ('GEOG','GEOG-Geography'***REMOVED***,
    ('GEOL', 'GEOL-Geology'***REMOVED***,
    ('GER', 'GER-German'***REMOVED***,
    ('GRC','GRC-Graphic Communication'***REMOVED***,
    ('GSB','GSB-Graduate Studies Business'***REMOVED***,
    ('HIST','HIST-History'***REMOVED***,
    ('HNRC', 'HNRC-Honors Contract'***REMOVED***,
    ('HNRS', 'HNRS-Honors'***REMOVED***,
    ('IME','IME-Industrial & Manufacturing Eng'***REMOVED***,
    ('ISLA','ISLA-Interdisc Stds in Liberal Arts'***REMOVED***,
    ('ITAL', 'ITAL-Italian'***REMOVED***,
    ('ITP','ITP-Industrial Tech and Packaging'***REMOVED***,
    ('JOUR','JOUR-Journalism'***REMOVED***,
    ('JPNS', 'JPNS-Japanese'***REMOVED***,
    ('KINE','KINE-Kinesiology'***REMOVED***,
    ('LA','LA-Landscape Architecture'***REMOVED***,
    ('LAES', 'LAES-Liberal Arts and Engr Studies'***REMOVED***,
    ('LS','LS-Liberal Studies'***REMOVED***,
    ('MATE','MATE-Materials Engineering'***REMOVED***,
    ('MATH','MATH-Mathematics'***REMOVED***,
    ('MCRO','MCRO-Microbiology'***REMOVED***,
    ('ME','ME-Mechanical Engineering'***REMOVED***,
    ('MSCI','MSCI-Marine Science'***REMOVED***,
    ('MSL', 'MSL-Military Science Leadership'***REMOVED***,
    ('MU','MU-Music'***REMOVED***,
    ('NR','NR-Natural Resources'***REMOVED***,
    ('PEM','PEM-Intercollegiate Athletics Men'***REMOVED***,
    ('PEW','PEW-Intercollegiate Athletics Women'***REMOVED***,
    ('PHIL','PHIL-Philosophy'***REMOVED***,
    ('PHYS','PHYS-Physics'***REMOVED***,
    ('POLS','POLS-Political Science'***REMOVED***,
    ('PSC','PSC-Physical Sciences'***REMOVED***,
    ('PSY','PSY-Psychology'***REMOVED***,
    ('RELS','RELS-Religious Studies'***REMOVED***,
    ('RPTA','RPTA-Rec, Parks & Tourism Admin'***REMOVED***,
    ('SCM', 'SCM-Science and Mathematics'***REMOVED***,
    ('SOC','SOC-Sociology'***REMOVED***,
    ('SOCS', 'SOCS-Social Sciences'***REMOVED***,
    ('SPAN','SPAN-Spanish'***REMOVED***,
    ('SS','SS-Soil Science'***REMOVED***,
    ('STAT','STAT-Statistics'***REMOVED***,
    ('TH','TH-Theatre'***REMOVED***,
    ('UNIV', 'UNIV-University Studies'***REMOVED***,
    ('WGS',"WGS-Women's and Gender Studies"***REMOVED***,
    ('WLC','WLC-World Languages and Cultures'***REMOVED***,
    ('WVIT','WVIT-Wine and Viticulture'***REMOVED***,
***REMOVED***

# Convert to dict for display purposes on tables. (Tuple is required for django choices***REMOVED***
departments = dict([[x.split('-'***REMOVED*** for x in choice***REMOVED***[1***REMOVED*** for choice in department_choices***REMOVED******REMOVED***

ge_areas = ['Show all GE',
            'B2B4-Gen Ed Areas B2 & B4',
            'B3B4-Gen Ed Areas B3 & B4',
            'GE-General Education',
            'GEA1-General Educ Area A1',
            'GEA2-General Educ Area A2',
            'GEA3-General Educ Area A3',
            'GEB1-General Educ Area B1',
            'GEB2-General Educ Area B2',
            'GEB3-General Educ Area B3',
            'GEB4-General Educ Area B4',
            'GEB5-General Educ Area B5',
            'GEB6-General Educ Area B6',
            'GEC-General Educ Area C',
            'GEC1-General Educ Area C1',
            'GEC2-General Educ Area C2',
            'GEC3-General Educ Area C3',
            'GEC4-General Educ Area C4',
            'GEC5-General Educ Area C5',
            'GED1-General Educ Area D1',
            'GED2-General Educ Area D2',
            'GED3-General Educ Area D3',
            'GED4-General Educ Area D4',
            'GED5-General Educ Area D5',
            'GEF-General Educ Area F***REMOVED***'***REMOVED***

area_choices = zip(ge_areas, ge_areas***REMOVED***

sort_choices = (
    ('Fewest Days', 'Fewest Days'***REMOVED***,
    ('Shortest Days', 'Shortest Days'***REMOVED***,
    ('Most Free Days', 'Most Free Days'***REMOVED***,
    ('Morning Classes', 'Morning Classes'***REMOVED***,
    ('Evening Classes', 'Evening Classes'***REMOVED***,
    ('Midday Classes', 'Midday Classes'***REMOVED***,
    ('Fewest Breaks', 'Fewest Breaks'***REMOVED***,
    ('Most Breaks', 'Most Breaks'***REMOVED***,
    ('Fewest Breaks', 'Fewest Breaks'***REMOVED***,
    ('Average Polrating', 'Average Polrating'***REMOVED***,
    ('Highest Polrating', 'Highest Polrating'***REMOVED***,
    ('Best Lowest Polyrating', 'Best Lowest Polyrating'***REMOVED***,
***REMOVED***
