CLOSED = 'closed'
CANCELLED = 'cancelled'
OPEN = 'open'
ANY = None

status_choices = (
    (ANY, 'Any'***REMOVED***,
    (OPEN, 'Open'***REMOVED***,
    (CLOSED, 'Closed'***REMOVED***,
    (CANCELLED, 'Cancelled'***REMOVED***,
***REMOVED***

department_choices = (
    (ANY, 'Any'***REMOVED***,
    ('AEPS', 'AEPS-Ag and Environmental Plant Sci'***REMOVED***,
    ('AERO','AERO-Aerospace Engineering'***REMOVED***,
    ('AGB','AGB-Agribusiness'***REMOVED***,
    ('AGC','AGC-Agricultural Communication'***REMOVED***,
    ('AGED','AGED-Agricultural Education'***REMOVED***,
    ('ANT','ANT-Anthropology'***REMOVED***,
    ('ARC','ARCE-Architectural Engineering'***REMOVED***,
    ('ARCH','ARCH-Architecture'***REMOVED***,
    ('ART','ART-Art'***REMOVED***,
    ('ASCI','ASCI-Animal Science'***REMOVED***,
    ('ASTR','ASTR-Astronomy'***REMOVED***,
    ('BIO','BIO-Biology'***REMOVED***,
    ('BMED','BMED-Biomedical Engineering'***REMOVED***,
    ('BRAE','BRAE-BioResource & Agricultural Eng'***REMOVED***,
    ('BUS','BUS-Business'***REMOVED***,
    ('CD','CD-Child Development'***REMOVED***,
    ('CE','CE-Civil Engineering'***REMOVED***,
    ('CHEM','CHEM-Chemistry'***REMOVED***,
    ('CM','CM-Construction Management'***REMOVED***,
    ('COMS','COMS-Communication Studies'***REMOVED***,
    ('CPE','CPE-Computer Engineering'***REMOVED***,
    ('CSC','CSC-Computer Science'***REMOVED***,
    ('DSCI','DSCI-Dairy Science'***REMOVED***,
    ('ECON','ECON-Economics'***REMOVED***,
    ('EDUC','EDUC-Education'***REMOVED***,
    ('EE','EE-Electrical Engineering'***REMOVED***,
    ('ENGL','ENGL-English'***REMOVED***,
    ('ENGR','ENGR-Engineering'***REMOVED***,
    ('ES','ES-Ethnic Studies'***REMOVED***,
    ('ESE','ESE-Early Start English'***REMOVED***,
    ('ESM','ESM-Early Start Math'***REMOVED***,
    ('FSN','FSN-Food Science and Nutrition'***REMOVED***,
    ('GEOG','GEOG-Geography'***REMOVED***,
    ('GRC','GRC-Graphic Communication'***REMOVED***,
    ('HIST','HIST-History'***REMOVED***,
    ('IME','IME-Industrial & Manufacturing Eng'***REMOVED***,
    ('ISLA','ISLA-Interdisc Stds in Liberal Arts'***REMOVED***,
    ('ITP','ITP-Industrial Tech and Packaging'***REMOVED***,
    ('JOUR','JOUR-Journalism'***REMOVED***,
    ('KINE','KINE-Kinesiology'***REMOVED***,
    ('LA','LA-Landscape Architecture'***REMOVED***,
    ('LS','LS-Liberal Studies'***REMOVED***,
    ('MATE','MATE-Materials Engineering'***REMOVED***,
    ('MATH','MATH-Mathematics'***REMOVED***,
    ('MCRO','MCRO-Microbiology'***REMOVED***,
    ('ME','ME-Mechanical Engineering'***REMOVED***,
    ('MSCI','MSCI-Marine Science'***REMOVED***,
    ('MU','MU-Music'***REMOVED***,
    ('NR','NR-Natural Resources'***REMOVED***,
    ('PHIL','PHIL-Philosophy'***REMOVED***,
    ('PHYS','PHYS-Physics'***REMOVED***,
    ('POLS','POLS-Political Science'***REMOVED***,
    ('PSY','PSY-Psychology'***REMOVED***,
    ('RPTA','RPTA-Rec, Parks & Tourism Admin'***REMOVED***,
    ('SOC','SOC-Sociology'***REMOVED***,
    ('SPAN','SPAN-Spanish'***REMOVED***,
    ('STAT','STAT-Statistics'***REMOVED***,
    ('TH','TH-Theatre'***REMOVED***,
    ('WGS',"WGS-Women's and Gender Studies"***REMOVED***,
    ('WLC','WLC-World Languages and Cultures'***REMOVED***,
    ('WVIT','WVIT-Wine and Viticulture'***REMOVED***,
***REMOVED***
