CLOSED = 'closed'
CANCELLED = 'cancelled'
OPEN = 'open'
ANY = None

status_choices = (
    (ANY, 'Any'***REMOVED***,
    (OPEN, 'Open'***REMOVED***,
    (CLOSED, 'Closed'***REMOVED***,
    (CANCELLED, 'Cancelled'***REMOVED***,
***REMOVED***

#TODO: Add the rest
department_choices = (
    ('AEPS', 'AEPS-Ag and Environmental Plant Sci'***REMOVED***,
    ('AERO','AERO-Aerospace Engineering'***REMOVED***,
    ('AGB','AGB-Agribusiness'***REMOVED***,
    ('AG','AG-Agriculture'***REMOVED***,
    ('AGC','AGC-Agricultural Communication'***REMOVED***,
    ('AGED','AGED-Agricultural Education'***REMOVED***,
    ('ANT','ANT-Anthropology'***REMOVED***,
    ('ARCE','ARCE-Architectural Engineering'***REMOVED***,
    ('ARCH','ARCH-Architecture'***REMOVED***,
    ('ART','ART-Art'***REMOVED***,
    ('ASCI','ASCI-Animal Science'***REMOVED***,
    ('ASTR','ASTR-Astronomy'***REMOVED***,
    ('BIO','BIO-Biology'***REMOVED***,
    ('BMED','BMED-Biomedical Engineering'***REMOVED***,
    ('BOT','BOT-Botany'***REMOVED***,
    ('BRAE','BRAE-BioResource & Agricultural Eng'***REMOVED***,
    ('BUS','BUS-Business'***REMOVED***,
    ('CD','CD-Child Development'***REMOVED***,
    ('CE','CE-Civil Engineering'***REMOVED***,
    ('CHEM','CHEM-Chemistry'***REMOVED***,
    ('CHIN','CHIN-Chinese'***REMOVED***,
    ('CM','CM-Construction Management'***REMOVED***,
    ('COMS','COMS-Communication Studies'***REMOVED***,
    ('CPE','CPE-Computer Engineering'***REMOVED***,
    ('CRP','CRP-City and Regional Planning'***REMOVED***,
    ('CSC','CSC-Computer Science'***REMOVED***,
    ('DSCI','DSCI-Dairy Science'***REMOVED***,
    ('ECON','ECON-Economics'***REMOVED***,
    ('EDUC','EDUC-Education'***REMOVED***,
    ('EE','EE-Electrical Engineering'***REMOVED***,
    ('ENGL','ENGL-English'***REMOVED***,
    ('ENGR','ENGR-Engineering'***REMOVED***,
    ('ES','ES-Ethnic Studies'***REMOVED***,
    ('ESE','ESE-Early Start English'***REMOVED***,
    ('ESM','ESM-Early Start Math'***REMOVED***,
    ('FSN','FSN-Food Science and Nutrition'***REMOVED***,
    ('GEOG','GEOG-Geography'***REMOVED***,
    ('GRC','GRC-Graphic Communication'***REMOVED***,
    ('HIST','HIST-History'***REMOVED***,
    ('IME','IME-Industrial & Manufacturing Eng'***REMOVED***,
    ('ISLA','ISLA-Interdisc Stds in Liberal Arts'***REMOVED***,
    ('ITP','ITP-Industrial Tech and Packaging'***REMOVED***,
    ('JOUR','JOUR-Journalism'***REMOVED***,
    ('KINE','KINE-Kinesiology'***REMOVED***,
    ('LA','LA-Landscape Architecture'***REMOVED***,
    ('LS','LS-Liberal Studies'***REMOVED***,
    ('MATE','MATE-Materials Engineering'***REMOVED***,
    ('MATH','MATH-Mathematics'***REMOVED***,
    ('MCRO','MCRO-Microbiology'***REMOVED***,
    ('ME','ME-Mechanical Engineering'***REMOVED***,
    ('MSCI','MSCI-Marine Science'***REMOVED***,
    ('MU','MU-Music'***REMOVED***,
    ('NR','NR-Natural Resources'***REMOVED***,
    ('PHIL','PHIL-Philosophy'***REMOVED***,
    ('PHYS','PHYS-Physics'***REMOVED***,
    ('POLS','POLS-Political Science'***REMOVED***,
    ('PSY','PSY-Psychology'***REMOVED***,
    ('RPTA','RPTA-Rec, Parks & Tourism Admin'***REMOVED***,
    ('SOC','SOC-Sociology'***REMOVED***,
    ('SPAN','SPAN-Spanish'***REMOVED***,
    ('STAT','STAT-Statistics'***REMOVED***,
    ('TH','TH-Theatre'***REMOVED***,
    ('WGS',"WGS-Women's and Gender Studies"***REMOVED***,
    ('WLC','WLC-World Languages and Cultures'***REMOVED***,
    ('WVIT','WVIT-Wine and Viticulture'***REMOVED***,
***REMOVED***

# Convert to dict for display purposes. (Tuple is required for django choices***REMOVED***
departments = dict([[x.split('-'***REMOVED*** for x in choice***REMOVED***[1***REMOVED*** for choice in department_choices***REMOVED******REMOVED***

ge_areas = ['Show all GE',
            'B2B4-Gen Ed Areas B2 & B4',
            'B3B4-Gen Ed Areas B3 & B4',
            'GE-General Education',
            'GEA1-General Educ Area A1',
            'GEA2-General Educ Area A2',
            'GEA3-General Educ Area A3',
            'GEB1-General Educ Area B1',
            'GEB2-General Educ Area B2',
            'GEB3-General Educ Area B3',
            'GEB4-General Educ Area B4',
            'GEB5-General Educ Area B5',
            'GEB6-General Educ Area B6',
            'GEC-General Educ Area C',
            'GEC1-General Educ Area C1',
            'GEC2-General Educ Area C2',
            'GEC3-General Educ Area C3',
            'GEC4-General Educ Area C4',
            'GEC5-General Educ Area C5',
            'GED1-General Educ Area D1',
            'GED2-General Educ Area D2',
            'GED3-General Educ Area D3',
            'GED4-General Educ Area D4',
            'GED5-General Educ Area D5',
            'GEF-General Educ Area F***REMOVED***'***REMOVED***

area_choices = zip(ge_areas, ge_areas***REMOVED***


# No longer needed due to list comprehension.
# Although it might end up being worth the speed later, so I'll save it.
# departments = {
#     'AEPS' : 'Ag and Environmental Plant Sci',
#     'AERO' : 'Aerospace Engineering',
#     'AGB'  : 'Agribusiness',
#     'AGC'  : 'Agricultural Communication',
#     'AGED' : 'Agricultural Education',
#     'ANT'  : 'Anthropology',
#     'ARCE' : 'Architectural Engineering',
#     'ARCH' : 'Architecture',
#     'ART'  : 'Art',
#     'ASCI' : 'Animal Science',
#     'ASTR' : 'Astronomy',
#     'BIO'  : 'Biology',
#     'BMED' : 'Biomedical Engineering',
#     'BRAE' : 'BioResource & Agricultural Eng',
#     'BUS'  : 'Business',
#     'CD'   : 'Child Development',
#     'CE'   : 'Civil Engineering',
#     'CHEM' : 'Chemistry',
#     'CM'   : 'Construction Management',
#     'COMS' : 'Communication Studies',
#     'CPE'  : 'Computer Engineering',
#     'CSC'  : 'Computer Science',
#     'DSCI' : 'Dairy Science',
#     'ECON' : 'Economics',
#     'EDUC' : 'Education',
#     'EE'   : 'Electrical Engineering',
#     'ENGL' : 'English',
#     'ENGR' : 'Engineering',
#     'ES'   : 'Ethnic Studies',
#     'ESE'  : 'Early Start English',
#     'ESM'  : 'Early Start Math',
#     'FSN'  : 'Food Science and Nutrition',
#     'GEOG' : 'Geography',
#     'GRC'  : 'Graphic Communication',
#     'HIST' : 'History',
#     'IME'  : 'Industrial & Manufacturing Eng',
#     'ISLA' : 'Interdisc Stds in Liberal Arts',
#     'ITP'  : 'Industrial Tech and Packaging',
#     'JOUR' : 'Journalism',
#     'KINE' : 'Kinesiology',
#     'LA'   : 'Landscape Architecture',
#     'LS'   : 'Liberal Studies',
#     'MATE' : 'Materials Engineering',
#     'MATH' : 'Mathematics',
#     'MCRO' : 'Microbiology',
#     'ME'   : 'Mechanical Engineering',
#     'MSCI' : 'Marine Science',
#     'MU'   : 'Music',
#     'NR'   : 'Natural Resources',
#     'PHIL' : 'Philosophy',
#     'PHYS' : 'Physics',
#     'POLS' : 'Political Science',
#     'PSY'  : 'Psychology',
#     'RPTA' : 'Rec, Parks & Tourism Admin',
#     'SOC'  : 'Sociology',
#     'SPAN' : 'Spanish',
#     'STAT' : 'Statistics',
#     'TH'   : 'Theatre',
#     'WGS'  : "Women's and Gender Studies",
#     'WLC'  : 'World Languages and Cultures',
#     'WVIT' : 'Wine and Viticulture',
# ***REMOVED***
