# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration***REMOVED***:

    dependencies = [
        ('polyprofile', '0001_initial'***REMOVED***,
    ***REMOVED***

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='checked',
        ***REMOVED***,
        migrations.RemoveField(
            model_name='profile',
            name='followed',
        ***REMOVED***,
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ***REMOVED***,
        migrations.DeleteModel(
            name='Profile',
        ***REMOVED***,
    ***REMOVED***
