# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration***REMOVED***:

    initial = True

    dependencies = [
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('class_field', models.IntegerField(db_column='class', primary_key=True, serialize=False***REMOVED******REMOVED***,
                ('course', models.CharField(blank=True, max_length=10, null=True***REMOVED******REMOVED***,
                ('course_num', models.IntegerField(***REMOVED******REMOVED***,
                ('sec_num', models.IntegerField(blank=True, null=True***REMOVED******REMOVED***,
                ('type', models.CharField(blank=True, max_length=3, null=True***REMOVED******REMOVED***,
                ('instructor', models.CharField(blank=True, max_length=50, null=True***REMOVED******REMOVED***,
                ('available', models.IntegerField(blank=True, null=True***REMOVED******REMOVED***,
                ('taken', models.IntegerField(blank=True, null=True***REMOVED******REMOVED***,
                ('waiting', models.IntegerField(blank=True, null=True***REMOVED******REMOVED***,
                ('status', models.CharField(blank=True, max_length=20, null=True***REMOVED******REMOVED***,
                ('days', models.CharField(blank=True, max_length=5, null=True***REMOVED******REMOVED***,
                ('start', models.TimeField(blank=True, null=True***REMOVED******REMOVED***,
                ('end', models.TimeField(blank=True, null=True***REMOVED******REMOVED***,
                ('building', models.CharField(blank=True, max_length=30, null=True***REMOVED******REMOVED***,
                ('room', models.CharField(blank=True, max_length=10, null=True***REMOVED******REMOVED***,
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True***REMOVED******REMOVED***,
            ***REMOVED***,
            options={
                'ordering': ['course', 'course_num', 'sec_num'***REMOVED***,
                'db_table': 'sections',
                'managed': False,
        ***REMOVED***,
        ***REMOVED***,
    ***REMOVED***
