# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration***REMOVED***:

    initial = True

    dependencies = [
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('data_id', models.IntegerField(primary_key=True, serialize=False***REMOVED******REMOVED***,
                ('course_ac', models.CharField(max_length=10***REMOVED******REMOVED***,
                ('course_num', models.CharField(max_length=10***REMOVED******REMOVED***,
                ('units', models.CharField(max_length=6***REMOVED******REMOVED***,
                ('course_description', models.CharField(max_length=150***REMOVED******REMOVED***,
                ('course_catalog_desc', models.CharField(max_length=1200***REMOVED******REMOVED***,
            ***REMOVED***,
            options={
                'db_table': 'courses_fall_2017',
                'managed': False,
        ***REMOVED***,
        ***REMOVED***,
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('class_field', models.SmallIntegerField(db_column='class', primary_key=True, serialize=False***REMOVED******REMOVED***,
                ('sec_num', models.SmallIntegerField(***REMOVED******REMOVED***,
                ('type', models.CharField(blank=True, max_length=3, null=True***REMOVED******REMOVED***,
                ('instructor', models.CharField(blank=True, max_length=50, null=True***REMOVED******REMOVED***,
                ('available', models.SmallIntegerField(blank=True, null=True***REMOVED******REMOVED***,
                ('taken', models.SmallIntegerField(blank=True, null=True***REMOVED******REMOVED***,
                ('waiting', models.SmallIntegerField(blank=True, null=True***REMOVED******REMOVED***,
                ('status', models.CharField(blank=True, max_length=20, null=True***REMOVED******REMOVED***,
                ('days', models.CharField(blank=True, max_length=5, null=True***REMOVED******REMOVED***,
                ('start', models.TimeField(blank=True, null=True***REMOVED******REMOVED***,
                ('end', models.TimeField(blank=True, null=True***REMOVED******REMOVED***,
                ('building', models.CharField(blank=True, max_length=30, null=True***REMOVED******REMOVED***,
                ('room', models.CharField(blank=True, max_length=10, null=True***REMOVED******REMOVED***,
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True***REMOVED******REMOVED***,
            ***REMOVED***,
            options={
                'ordering': ('course__course_ac', 'course__course_num', 'sec_num'***REMOVED***,
                'db_table': 'sections_fall_2017',
                'managed': False,
        ***REMOVED***,
        ***REMOVED***,
    ***REMOVED***
