# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration***REMOVED***:

    dependencies = [
        ('polysearch', '0001_initial'***REMOVED***,
    ***REMOVED***

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='scrape_courses_fall_2017',
        ***REMOVED***,
        migrations.AlterModelTable(
            name='sections',
            table='scrape_sections_fall_2017',
        ***REMOVED***,
    ***REMOVED***
