# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration***REMOVED***:

    dependencies = [
        ('polysearch', '0001_initial'***REMOVED***,
    ***REMOVED***

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('course', models.CharField(max_length=10, primary_key=True, serialize=False***REMOVED******REMOVED***,
                ('description', models.CharField(blank=True, max_length=100, null=True***REMOVED******REMOVED***,
            ***REMOVED***,
            options={
                'db_table': 'descriptions',
                'managed': False,
        ***REMOVED***,
        ***REMOVED***,
        migrations.AlterModelTable(
            name='sections',
            table='fall_2017_sections',
        ***REMOVED***,
    ***REMOVED***
