# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration***REMOVED***:

    dependencies = [
        ('polysearch', '0002_auto_20170816_2049'***REMOVED***,
    ***REMOVED***

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'managed': False***REMOVED***,
        ***REMOVED***,
    ***REMOVED***
