# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration***REMOVED***:

    dependencies = [
        ('polysearch', '0003_auto_20170816_2343'***REMOVED***,
    ***REMOVED***

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': False, 'ordering': ('course_ac', 'course_num'***REMOVED******REMOVED***,
        ***REMOVED***,
        migrations.AlterModelOptions(
            name='sections',
            options={'managed': False, 'ordering': ('course_id__course_ac', 'course_id__course_num', 'sec_num'***REMOVED******REMOVED***,
        ***REMOVED***,
    ***REMOVED***
